// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EatTogether.API.Models.EfModels;

public partial class ArticleCategory
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int SortOrder { get; set; }

    public bool IsEnabled { get; set; }

    public virtual ICollection<Article> Articles { get; set; } = new List<Article>();
}