// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EatTogether.API.Models.EfModels;

public partial class EatTogetherDBContext : DbContext
{
	public EatTogetherDBContext(DbContextOptions<EatTogetherDBContext> options)
		: base(options)
	{
	}

	public virtual DbSet<Article> Articles { get; set; }

	public virtual DbSet<ArticleCategory> ArticleCategories { get; set; }

	public virtual DbSet<Category> Categories { get; set; }

	public virtual DbSet<Coupon> Coupons { get; set; }

	public virtual DbSet<Dish> Dishes { get; set; }

	public virtual DbSet<EmailQueue> EmailQueues { get; set; }

	public virtual DbSet<Event> Events { get; set; }

	public virtual DbSet<Function> Functions { get; set; }

	public virtual DbSet<Member> Members { get; set; }

	public virtual DbSet<MemberConfirmToken> MemberConfirmTokens { get; set; }

	public virtual DbSet<MemberCoupon> MemberCoupons { get; set; }

	public virtual DbSet<MemberExternalLogin> MemberExternalLogins { get; set; }

	public virtual DbSet<MemberFavorite> MemberFavorites { get; set; }

	public virtual DbSet<MemberPasswordResetToken> MemberPasswordResetTokens { get; set; }

	public virtual DbSet<MemberRefreshToken> MemberRefreshTokens { get; set; }

	public virtual DbSet<Order> Orders { get; set; }

	public virtual DbSet<OrderDetail> OrderDetails { get; set; }

	public virtual DbSet<PasswordResetToken> PasswordResetTokens { get; set; }

	public virtual DbSet<Payment> Payments { get; set; }

	public virtual DbSet<PreOrder> PreOrders { get; set; }

	public virtual DbSet<PreOrderDetail> PreOrderDetails { get; set; }

	public virtual DbSet<Product> Products { get; set; }

	public virtual DbSet<Reservation> Reservations { get; set; }

	public virtual DbSet<Review> Reviews { get; set; }

	public virtual DbSet<Role> Roles { get; set; }

	public virtual DbSet<RoleFunction> RoleFunctions { get; set; }

	public virtual DbSet<SchedulerLog> SchedulerLogs { get; set; }

	public virtual DbSet<SetMeal> SetMeals { get; set; }

	public virtual DbSet<SetMealItem> SetMealItems { get; set; }

	public virtual DbSet<SubscriptionPreference> SubscriptionPreferences { get; set; }

	public virtual DbSet<Table> Tables { get; set; }

	public virtual DbSet<User> Users { get; set; }

	public virtual DbSet<UserNotification> UserNotifications { get; set; }

	public virtual DbSet<UserRole> UserRoles { get; set; }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Article>(entity =>
		{
			entity.HasIndex(e => e.PublishDate, "IX_Articles_PublishDate");

			entity.HasIndex(e => e.Status, "IX_Articles_Status");

			entity.Property(e => e.CoverImageUrl).HasMaxLength(255);
			entity.Property(e => e.Description).IsRequired();
			entity.Property(e => e.ExpiryDate).HasPrecision(0);
			entity.Property(e => e.PublishDate).HasPrecision(0);
			entity.Property(e => e.Title)
				.IsRequired()
				.HasMaxLength(200);

			entity.HasOne(d => d.Category).WithMany(p => p.Articles)
				.HasForeignKey(d => d.CategoryId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_Articles_Categories");

			entity.HasOne(d => d.Event).WithMany(p => p.Articles)
				.HasForeignKey(d => d.EventId)
				.HasConstraintName("FK_Articles_Events");
		});

		modelBuilder.Entity<ArticleCategory>(entity =>
		{
			entity.HasIndex(e => e.Name, "IX_ArticleCategories_Name").IsUnique();

			entity.HasIndex(e => e.SortOrder, "IX_ArticleCategories_Sort");

			entity.Property(e => e.IsEnabled).HasDefaultValue(true);
			entity.Property(e => e.Name)
				.IsRequired()
				.HasMaxLength(50);
		});

		modelBuilder.Entity<Category>(entity =>
		{
			entity.Property(e => e.CategoryName)
				.IsRequired()
				.HasMaxLength(50);
			entity.Property(e => e.CreatedAt)
				.HasPrecision(0)
				.HasDefaultValueSql("(getdate())");
			entity.Property(e => e.IsActive).HasDefaultValue(true);
			entity.Property(e => e.UpdatedAt).HasPrecision(0);

			entity.HasOne(d => d.ParentCategory).WithMany(p => p.InverseParentCategory)
				.HasForeignKey(d => d.ParentCategoryId)
				.HasConstraintName("FK_Categories_Parent");
		});

		modelBuilder.Entity<Coupon>(entity =>
		{
			entity.HasIndex(e => e.Code, "IX_Coupons_Code").IsUnique();

			entity.Property(e => e.Code)
				.IsRequired()
				.HasMaxLength(20)
				.IsUnicode(false);
			entity.Property(e => e.EndDate).HasPrecision(0);
			entity.Property(e => e.Name)
				.IsRequired()
				.HasMaxLength(50);
			entity.Property(e => e.StartDate).HasPrecision(0);
		});

		modelBuilder.Entity<Dish>(entity =>
		{
			entity.Property(e => e.CreatedAt)
				.HasPrecision(0)
				.HasDefaultValueSql("(getdate())");
			entity.Property(e => e.Description).HasMaxLength(300);
			entity.Property(e => e.DishName)
				.IsRequired()
				.HasMaxLength(100);
			entity.Property(e => e.IsActive).HasDefaultValue(true);
			entity.Property(e => e.IsTakeOut).HasDefaultValue(true);
			entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
			entity.Property(e => e.UpdatedAt).HasPrecision(0);

			entity.HasOne(d => d.Category).WithMany(p => p.Dishes)
				.HasForeignKey(d => d.CategoryId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_Dishes_Categories");
		});

		modelBuilder.Entity<EmailQueue>(entity =>
		{
			entity.HasIndex(e => e.RecipientEmail, "IX_EmailQueues_Recipient");

			entity.HasIndex(e => e.Status, "IX_EmailQueues_Status");

			entity.Property(e => e.Body).IsRequired();
			entity.Property(e => e.CreatedAt)
				.HasPrecision(0)
				.HasDefaultValueSql("(getdate())");
			entity.Property(e => e.ProcessedAt).HasPrecision(0);
			entity.Property(e => e.RecipientEmail)
				.IsRequired()
				.HasMaxLength(100);
			entity.Property(e => e.Subject)
				.IsRequired()
				.HasMaxLength(200);
		});

		modelBuilder.Entity<Event>(entity =>
		{
			entity.HasIndex(e => e.StartDate, "IX_Events_StartDate");

			entity.HasIndex(e => e.Status, "IX_Events_Status");

			entity.Property(e => e.DiscountType)
				.IsRequired()
				.HasMaxLength(20);
			entity.Property(e => e.DiscountValue).HasColumnType("decimal(10, 2)");
			entity.Property(e => e.EndDate).HasPrecision(0);
			entity.Property(e => e.IsAutoDiscount).HasDefaultValue(1);
			entity.Property(e => e.StartDate).HasPrecision(0);
			entity.Property(e => e.Summary)
				.IsRequired()
				.HasMaxLength(50);
			entity.Property(e => e.Title)
				.IsRequired()
				.HasMaxLength(100);

			entity.HasOne(d => d.RewardDish).WithMany(p => p.Events)
				.HasForeignKey(d => d.RewardDishId)
				.HasConstraintName("FK_Events_Dishes");
		});

		modelBuilder.Entity<Function>(entity =>
		{
			entity.HasIndex(e => e.FunctionName, "IX_Functions_FunctionName").IsUnique();

			entity.Property(e => e.Category)
				.IsRequired()
				.HasMaxLength(10);
			entity.Property(e => e.Description).HasMaxLength(200);
			entity.Property(e => e.DisplayName)
				.IsRequired()
				.HasMaxLength(50);
			entity.Property(e => e.FunctionName)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.IsOwnerOnly).HasAnnotation("Relational:DefaultConstraintName", "DF_Functions_IsOwnerOnly");
		});

		modelBuilder.Entity<Member>(entity =>
		{
			entity.HasIndex(e => e.Account, "IX_Members_Account").IsUnique();

			entity.HasIndex(e => e.Email, "IX_Members_Email").IsUnique();

			entity.HasIndex(e => e.IsDeleted, "IX_Members_IsDeleted");

			entity.Property(e => e.Account)
				.IsRequired()
				.HasMaxLength(100)
				.IsUnicode(false);
			entity.Property(e => e.AvatarFileName)
				.HasMaxLength(100)
				.IsUnicode(false)
				.HasDefaultValueSql("(NULL)")
				.HasAnnotation("Relational:DefaultConstraintName", "DF_Members_AvatarFileName");
			entity.Property(e => e.BlacklistReason)
				.HasMaxLength(200)
				.HasDefaultValueSql("(NULL)")
				.HasAnnotation("Relational:DefaultConstraintName", "DF_Members_BlacklistReason");
			entity.Property(e => e.CreatedAt)
				.HasPrecision(0)
				.HasDefaultValueSql("(getdate())")
				.HasAnnotation("Relational:DefaultConstraintName", "DF__Members__Created__114A936A");
			entity.Property(e => e.DeletedAt).HasPrecision(0);
			entity.Property(e => e.Email)
				.IsRequired()
				.HasMaxLength(100)
				.IsUnicode(false);
			entity.Property(e => e.HashedPassword)
				.IsRequired()
				.HasMaxLength(70)
				.IsUnicode(false);
			entity.Property(e => e.IsBlacklisted).HasAnnotation("Relational:DefaultConstraintName", "DF__Members__IsBlack__10566F31");
			entity.Property(e => e.IsConfirmed).HasAnnotation("Relational:DefaultConstraintName", "DF_Members_IsConfirmed");
			entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF__Members__IsDelet__123EB7A3");
			entity.Property(e => e.Name)
				.IsRequired()
				.HasMaxLength(50);
			entity.Property(e => e.Phone)
				.HasMaxLength(10)
				.IsUnicode(false);
		});

		modelBuilder.Entity<MemberConfirmToken>(entity =>
		{
			entity.HasIndex(e => e.MemberId, "IX_MemberConfirmTokens_MemberId");

			entity.HasIndex(e => e.Token, "IX_MemberConfirmTokens_Token").IsUnique();

			entity.Property(e => e.CreatedAt)
				.HasPrecision(0)
				.HasDefaultValueSql("(getdate())");
			entity.Property(e => e.ExpiresAt).HasPrecision(0);
			entity.Property(e => e.NewEmail)
				.HasMaxLength(100)
				.IsUnicode(false);
			entity.Property(e => e.Token)
				.IsRequired()
				.HasMaxLength(32)
				.IsUnicode(false);

			entity.HasOne(d => d.Member).WithMany(p => p.MemberConfirmTokens)
				.HasForeignKey(d => d.MemberId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_MemberConfirmTokens_Members");
		});

		modelBuilder.Entity<MemberCoupon>(entity =>
		{
			entity.Property(e => e.ClaimedAt).HasPrecision(0);
			entity.Property(e => e.UsedDate).HasPrecision(0);

			entity.HasOne(d => d.Coupon).WithMany(p => p.MemberCoupons)
				.HasForeignKey(d => d.CouponId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_MemberCoupons_Coupons");

			entity.HasOne(d => d.Member).WithMany(p => p.MemberCoupons)
				.HasForeignKey(d => d.MemberId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_MemberCoupons_Members");
		});

		modelBuilder.Entity<MemberExternalLogin>(entity =>
		{
			entity.HasIndex(e => new { e.MemberId, e.Provider }, "IX_MemberExternalLogins_MemberId_Provider").IsUnique();

			entity.HasIndex(e => new { e.Provider, e.ProviderUserId }, "IX_MemberExternalLogins_Provider_ProviderUserId").IsUnique();

			entity.Property(e => e.AvatarUrl).HasMaxLength(500);
			entity.Property(e => e.CreatedAt)
				.HasPrecision(0)
				.HasDefaultValueSql("(getdate())");
			entity.Property(e => e.Provider)
				.IsRequired()
				.HasMaxLength(20)
				.IsUnicode(false);
			entity.Property(e => e.ProviderUserId)
				.IsRequired()
				.HasMaxLength(100)
				.IsUnicode(false);

			entity.HasOne(d => d.Member).WithMany(p => p.MemberExternalLogins)
				.HasForeignKey(d => d.MemberId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_MemberExternalLogins_Members");
		});

		modelBuilder.Entity<MemberFavorite>(entity =>
		{
			entity.HasIndex(e => new { e.MemberId, e.ProductId }, "IX_MemberFavorites_Mem_Prod").IsUnique();

			entity.Property(e => e.CreatedAt)
				.HasPrecision(0)
				.HasDefaultValueSql("(getdate())");

			entity.HasOne(d => d.Member).WithMany(p => p.MemberFavorites)
				.HasForeignKey(d => d.MemberId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_MemberFavorites_Members");

			entity.HasOne(d => d.Product).WithMany(p => p.MemberFavorites)
				.HasForeignKey(d => d.ProductId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_MemberFavorites_Products");
		});

		modelBuilder.Entity<MemberPasswordResetToken>(entity =>
		{
			entity.HasIndex(e => e.MemberId, "IX_MemberPasswordResetTokens_MemberId");

			entity.HasIndex(e => e.Token, "IX_MemberPasswordResetTokens_Token").IsUnique();

			entity.Property(e => e.CreatedAt)
				.HasPrecision(0)
				.HasDefaultValueSql("(getdate())");
			entity.Property(e => e.ExpiresAt).HasPrecision(0);
			entity.Property(e => e.Token)
				.IsRequired()
				.HasMaxLength(32)
				.IsUnicode(false);

			entity.HasOne(d => d.Member).WithMany(p => p.MemberPasswordResetTokens)
				.HasForeignKey(d => d.MemberId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_MemberPasswordResetTokens_Members");
		});

		modelBuilder.Entity<MemberRefreshToken>(entity =>
		{
			entity.HasIndex(e => e.MemberId, "IX_MemberRefreshTokens_MemberId");

			entity.HasIndex(e => e.Token, "IX_MemberRefreshTokens_Token").IsUnique();

			entity.Property(e => e.CreatedAt)
				.HasPrecision(0)
				.HasDefaultValueSql("(getdate())");
			entity.Property(e => e.ExpiresAt).HasPrecision(0);
			entity.Property(e => e.Token)
				.IsRequired()
				.HasMaxLength(64)
				.IsUnicode(false);

			entity.HasOne(d => d.Member).WithMany(p => p.MemberRefreshTokens)
				.HasForeignKey(d => d.MemberId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_MemberRefreshTokens_Members");
		});

		modelBuilder.Entity<Order>(entity =>
		{
			entity.HasIndex(e => e.OrderAt, "IX_Orders_OrderAt");

			entity.HasIndex(e => e.OrderNumber, "IX_Orders_OrderNumber").IsUnique();

			entity.Property(e => e.OrderAt)
				.HasPrecision(0)
				.HasDefaultValueSql("(getdate())");
			entity.Property(e => e.OrderNumber)
				.IsRequired()
				.HasMaxLength(200);
			entity.Property(e => e.PayMethod)
				.IsRequired()
				.HasMaxLength(50);

			entity.HasOne(d => d.Coupon).WithMany(p => p.Orders)
				.HasForeignKey(d => d.CouponId)
				.HasConstraintName("FK_Orders_Coupons");

			entity.HasOne(d => d.Member).WithMany(p => p.Orders)
				.HasForeignKey(d => d.MemberId)
				.HasConstraintName("FK_Orders_Members");

			entity.HasOne(d => d.Payment).WithMany(p => p.Orders)
				.HasForeignKey(d => d.PaymentId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_Orders_Payments");

			entity.HasOne(d => d.PreOrder).WithMany(p => p.Orders)
				.HasForeignKey(d => d.PreOrderId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_Orders_PreOrders");

			entity.HasOne(d => d.Table).WithMany(p => p.Orders)
				.HasForeignKey(d => d.TableId)
				.HasConstraintName("FK_Orders_Tables");

			entity.HasOne(d => d.User).WithMany(p => p.Orders)
				.HasForeignKey(d => d.UserId)
				.HasConstraintName("FK_Orders_Users");
		});

		modelBuilder.Entity<OrderDetail>(entity =>
		{
			entity.Property(e => e.ProductName)
				.IsRequired()
				.HasMaxLength(50);
			entity.Property(e => e.Qty).HasDefaultValue(1);

			entity.HasOne(d => d.Order).WithMany(p => p.OrderDetails)
				.HasForeignKey(d => d.OrderId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_OrderDetails_Orders");

			entity.HasOne(d => d.Product).WithMany(p => p.OrderDetails)
				.HasForeignKey(d => d.ProductId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_OrderDetails_Products");
		});

		modelBuilder.Entity<PasswordResetToken>(entity =>
		{
			entity.HasIndex(e => e.Token, "IX_PasswordResetTokens_Token").IsUnique();

			entity.HasIndex(e => e.UserId, "IX_PasswordResetTokens_UserId");

			entity.Property(e => e.CreatedAt)
				.HasPrecision(0)
				.HasDefaultValueSql("(getdate())")
				.HasAnnotation("Relational:DefaultConstraintName", "DF_PasswordResetTokens_CreatedAt");
			entity.Property(e => e.ExpiresAt).HasPrecision(0);
			entity.Property(e => e.IsUsed).HasAnnotation("Relational:DefaultConstraintName", "DF_PasswordResetTokens_IsUsed");
			entity.Property(e => e.Token)
				.IsRequired()
				.HasMaxLength(32)
				.IsUnicode(false);

			entity.HasOne(d => d.User).WithMany(p => p.PasswordResetTokens)
				.HasForeignKey(d => d.UserId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_PasswordResetTokens_Users");
		});

		modelBuilder.Entity<Payment>(entity =>
		{
			entity.Property(e => e.Method)
				.IsRequired()
				.HasMaxLength(50);
			entity.Property(e => e.PaidAt)
				.HasPrecision(0)
				.HasDefaultValueSql("(getdate())");

			entity.HasOne(d => d.Order).WithMany(p => p.Payments)
				.HasForeignKey(d => d.OrderId)
				.HasConstraintName("FK_Payments_Orders");

			entity.HasOne(d => d.PreOrder).WithMany(p => p.Payments)
				.HasForeignKey(d => d.PreOrderId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_Payments_PreOrders");
		});

		modelBuilder.Entity<PreOrder>(entity =>
		{
			entity.HasIndex(e => e.OrderAt, "IX_PreOrders_OrderAt");

			entity.HasIndex(e => e.OrderNumber, "IX_PreOrders_OrderNumber").IsUnique();

			entity.Property(e => e.CancelledAt).HasPrecision(0);
			entity.Property(e => e.OrderAt)
				.HasPrecision(0)
				.HasDefaultValueSql("(getdate())");
			entity.Property(e => e.OrderNumber)
				.IsRequired()
				.HasMaxLength(200);
			entity.Property(e => e.PayMethod)
				.IsRequired()
				.HasMaxLength(50);

			entity.HasOne(d => d.Coupon).WithMany(p => p.PreOrders)
				.HasForeignKey(d => d.CouponId)
				.HasConstraintName("FK_PreOrders_Coupons");

			entity.HasOne(d => d.Event).WithMany(p => p.PreOrders)
				.HasForeignKey(d => d.EventId)
				.HasConstraintName("FK_PreOrders_Events");

			entity.HasOne(d => d.Member).WithMany(p => p.PreOrders)
				.HasForeignKey(d => d.MemberId)
				.HasConstraintName("FK_PreOrders_Members");

			entity.HasOne(d => d.Payment).WithMany(p => p.PreOrders)
				.HasForeignKey(d => d.PaymentId)
				.HasConstraintName("FK_PreOrders_Payments");

			entity.HasOne(d => d.Table).WithMany(p => p.PreOrders)
				.HasForeignKey(d => d.TableId)
				.HasConstraintName("FK_PreOrders_Tables");

			entity.HasOne(d => d.User).WithMany(p => p.PreOrders)
				.HasForeignKey(d => d.UserId)
				.HasConstraintName("FK_PreOrders_Users");
		});

		modelBuilder.Entity<PreOrderDetail>(entity =>
		{
			entity.Property(e => e.ProductName)
				.IsRequired()
				.HasMaxLength(50);
			entity.Property(e => e.Qty).HasDefaultValue(1);

			entity.HasOne(d => d.ParentDetail).WithMany(p => p.InverseParentDetail)
				.HasForeignKey(d => d.ParentDetailId)
				.HasConstraintName("FK_PreOrderDetails_Parent");

			entity.HasOne(d => d.PreOrder).WithMany(p => p.PreOrderDetails)
				.HasForeignKey(d => d.PreOrderId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_PreOrderDetails_PreOrders");

			entity.HasOne(d => d.Product).WithMany(p => p.PreOrderDetails)
				.HasForeignKey(d => d.ProductId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_PreOrderDetails_Products");
		});

		modelBuilder.Entity<Product>(entity =>
		{
			entity.Property(e => e.ProductType)
				.IsRequired()
				.HasMaxLength(10);

			entity.HasOne(d => d.Dish).WithMany(p => p.Products)
				.HasForeignKey(d => d.DishId)
				.HasConstraintName("FK_Products_Dishes");

			entity.HasOne(d => d.SetMeal).WithMany(p => p.Products)
				.HasForeignKey(d => d.SetMealId)
				.HasConstraintName("FK_Products_SetMeals");
		});

		modelBuilder.Entity<Reservation>(entity =>
		{
			entity.HasIndex(e => e.BookingNumber, "IX_Reservations_BookingNumber").IsUnique();

			entity.HasIndex(e => e.ReservationDate, "IX_Reservations_Date");

			entity.Property(e => e.AdultsCount).HasDefaultValue(1);
			entity.Property(e => e.BookingNumber)
				.IsRequired()
				.HasMaxLength(10)
				.IsUnicode(false);
			entity.Property(e => e.CancelledAt).HasPrecision(0);
			entity.Property(e => e.Email)
				.IsRequired()
				.HasMaxLength(100)
				.IsUnicode(false);
			entity.Property(e => e.Name)
				.IsRequired()
				.HasMaxLength(50);
			entity.Property(e => e.Phone)
				.IsRequired()
				.HasMaxLength(20)
				.IsUnicode(false);
			entity.Property(e => e.Remark).HasMaxLength(200);
			entity.Property(e => e.ReservationDate).HasPrecision(0);
			entity.Property(e => e.ReservedAt)
				.HasPrecision(0)
				.HasDefaultValueSql("(getdate())");

			entity.HasOne(d => d.Member).WithMany(p => p.Reservations)
				.HasForeignKey(d => d.MemberId)
				.HasConstraintName("FK_Reservations_Members");
		});

		modelBuilder.Entity<Review>(entity =>
		{
			entity.Property(e => e.Content)
				.IsRequired()
				.HasMaxLength(200);
			entity.Property(e => e.CreatedAt)
				.HasPrecision(0)
				.HasDefaultValueSql("(getdate())");
			entity.Property(e => e.Nickname)
				.IsRequired()
				.HasMaxLength(20);

			entity.HasOne(d => d.Dish).WithMany(p => p.Reviews)
				.HasForeignKey(d => d.DishId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_Reviews_Dishes");
		});

		modelBuilder.Entity<Role>(entity =>
		{
			entity.HasIndex(e => e.RoleName, "IX_Roles_RoleName").IsUnique();

			entity.Property(e => e.CreatedAt)
				.HasPrecision(0)
				.HasDefaultValueSql("(getdate())");
			entity.Property(e => e.Description).HasMaxLength(100);
			entity.Property(e => e.RoleName)
				.IsRequired()
				.HasMaxLength(20);
		});

		modelBuilder.Entity<RoleFunction>(entity =>
		{
			entity.HasIndex(e => new { e.RoleId, e.FunctionId }, "IX_RoleFunctions_Role_Func").IsUnique();

			entity.HasOne(d => d.Function).WithMany(p => p.RoleFunctions)
				.HasForeignKey(d => d.FunctionId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_RoleFunctions_Functions");

			entity.HasOne(d => d.Role).WithMany(p => p.RoleFunctions)
				.HasForeignKey(d => d.RoleId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_RoleFunctions_Roles");
		});

		modelBuilder.Entity<SchedulerLog>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK__Schedule__3214EC0756A3AD04");

			entity.Property(e => e.ExecutedAt)
				.HasDefaultValueSql("(getdate())")
				.HasColumnType("datetime");
			entity.Property(e => e.TriggerType)
				.IsRequired()
				.HasMaxLength(10)
				.HasDefaultValue("自動");
		});

		modelBuilder.Entity<SetMeal>(entity =>
		{
			entity.Property(e => e.CreatedAt)
				.HasDefaultValueSql("(getdate())")
				.HasColumnType("datetime");
			entity.Property(e => e.Description).HasMaxLength(300);
			entity.Property(e => e.DiscountType)
				.IsRequired()
				.HasMaxLength(20);
			entity.Property(e => e.DiscountValue).HasColumnType("decimal(10, 2)");
			entity.Property(e => e.DisplayOrder).HasDefaultValue(1);
			entity.Property(e => e.IsActive).HasDefaultValue(true);
			entity.Property(e => e.SetMealName)
				.IsRequired()
				.HasMaxLength(100);
			entity.Property(e => e.SetPrice).HasColumnType("decimal(10, 2)");
			entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
		});

		modelBuilder.Entity<SetMealItem>(entity =>
		{
			entity.Property(e => e.Quantity).HasDefaultValue(1);

			entity.HasOne(d => d.Dish).WithMany(p => p.SetMealItems)
				.HasForeignKey(d => d.DishId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_SetMealItems_Dishes");

			entity.HasOne(d => d.SetMeal).WithMany(p => p.SetMealItems)
				.HasForeignKey(d => d.SetMealId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_SetMealItems_SetMeals");
		});

		modelBuilder.Entity<SubscriptionPreference>(entity =>
		{
			entity.Property(e => e.IsEmailSubscribed).HasDefaultValue(true);
			entity.Property(e => e.IsPushSubscribed).HasDefaultValue(true);
			entity.Property(e => e.UpdatedAt)
				.HasPrecision(0)
				.HasDefaultValueSql("(getdate())");

			entity.HasOne(d => d.Member).WithMany(p => p.SubscriptionPreferences)
				.HasForeignKey(d => d.MemberId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_SubscriptionPreferences_Members");
		});

		modelBuilder.Entity<Table>(entity =>
		{
			entity.HasIndex(e => e.TableName, "IX_Tables_TableName").IsUnique();

			entity.Property(e => e.Remark).HasMaxLength(200);
			entity.Property(e => e.SeatCount).HasDefaultValue(2);
			entity.Property(e => e.TableName)
				.IsRequired()
				.HasMaxLength(20);
		});

		modelBuilder.Entity<User>(entity =>
		{
			entity.HasIndex(e => e.Account, "IX_Users_Account").IsUnique();

			entity.HasIndex(e => e.Email, "IX_Users_Email").IsUnique();

			entity.HasIndex(e => e.EmployeeNumber, "IX_Users_EmployeeNumber").IsUnique();

			entity.Property(e => e.Account)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.CreatedAt)
				.HasPrecision(0)
				.HasDefaultValueSql("(getdate())")
				.HasAnnotation("Relational:DefaultConstraintName", "DF__Users__CreatedAt__32AB8735");
			entity.Property(e => e.Email)
				.IsRequired()
				.HasMaxLength(100)
				.IsUnicode(false);
			entity.Property(e => e.EmployeeNumber)
				.IsRequired()
				.HasMaxLength(20)
				.IsUnicode(false);
			entity.Property(e => e.HashedPassword)
				.IsRequired()
				.HasMaxLength(70)
				.IsUnicode(false);
			entity.Property(e => e.IsActive)
				.HasDefaultValue(true)
				.HasAnnotation("Relational:DefaultConstraintName", "DF__Users__IsActive__339FAB6E");
			entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF__Users__IsDeleted__3493CFA7");
			entity.Property(e => e.MustChangePassword).HasAnnotation("Relational:DefaultConstraintName", "DF_Users_MustChangePassword");
			entity.Property(e => e.Name)
				.IsRequired()
				.HasMaxLength(50);
			entity.Property(e => e.Phone)
				.IsRequired()
				.HasMaxLength(10)
				.IsUnicode(false);
		});

		modelBuilder.Entity<UserNotification>(entity =>
		{
			entity.HasIndex(e => e.IsRead, "IX_UserNotifications_IsRead");

			entity.HasIndex(e => e.MemberId, "IX_UserNotifications_MemberId");

			entity.Property(e => e.CreatedAt)
				.HasPrecision(0)
				.HasDefaultValueSql("(getdate())");
			entity.Property(e => e.Title)
				.IsRequired()
				.HasMaxLength(200);

			entity.HasOne(d => d.Article).WithMany(p => p.UserNotifications)
				.HasForeignKey(d => d.ArticleId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_UserNotifications_Articles");

			entity.HasOne(d => d.Member).WithMany(p => p.UserNotifications)
				.HasForeignKey(d => d.MemberId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_UserNotifications_Members");
		});

		modelBuilder.Entity<UserRole>(entity =>
		{
			entity.HasIndex(e => new { e.UserId, e.RoleId }, "IX_UserRoles_User_Role").IsUnique();

			entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
				.HasForeignKey(d => d.RoleId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_UserRoles_Roles");

			entity.HasOne(d => d.User).WithMany(p => p.UserRoles)
				.HasForeignKey(d => d.UserId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_UserRoles_Users");
		});

		OnModelCreatingPartial(modelBuilder);
	}

	partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}