// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EatTogether.API.Models.EfModels;

public partial class EmailQueue
{
    public int Id { get; set; }

    public string RecipientEmail { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }

    public int Status { get; set; }

    public DateTime? ProcessedAt { get; set; }

    public DateTime CreatedAt { get; set; }
}