// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EatTogether.API.Models.EfModels;

public partial class Event
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Summary { get; set; }

    public int MinSpend { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public int? RewardDishId { get; set; }

    public string DiscountType { get; set; }

    public decimal DiscountValue { get; set; }

    public int Status { get; set; }

    public int IsAutoDiscount { get; set; }

    public virtual ICollection<Article> Articles { get; set; } = new List<Article>();

    public virtual ICollection<PreOrder> PreOrders { get; set; } = new List<PreOrder>();

    public virtual Dish RewardDish { get; set; }
}