// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EatTogether.API.Models.EfModels;

public partial class Function
{
    public int Id { get; set; }

    public string Category { get; set; }

    public string FunctionName { get; set; }

    public string DisplayName { get; set; }

    public string Description { get; set; }

    public bool IsOwnerOnly { get; set; }

    public virtual ICollection<RoleFunction> RoleFunctions { get; set; } = new List<RoleFunction>();
}