// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EatTogether.API.Models.EfModels;

public partial class MemberExternalLogin
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public string Provider { get; set; }

    public string ProviderUserId { get; set; }

    public string AvatarUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Member Member { get; set; }
}