// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EatTogether.API.Models.EfModels;

public partial class Member
{
    public int Id { get; set; }

    public string Account { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string HashedPassword { get; set; }

    public string Phone { get; set; }

    public DateOnly? BirthDate { get; set; }

    public bool IsBlacklisted { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool IsConfirmed { get; set; }

    public string AvatarFileName { get; set; }

    public string BlacklistReason { get; set; }

    public virtual ICollection<LimitedNotification> LimitedNotifications { get; set; } = new List<LimitedNotification>();

    public virtual ICollection<MemberConfirmToken> MemberConfirmTokens { get; set; } = new List<MemberConfirmToken>();

    public virtual ICollection<MemberCoupon> MemberCoupons { get; set; } = new List<MemberCoupon>();

    public virtual ICollection<MemberExternalLogin> MemberExternalLogins { get; set; } = new List<MemberExternalLogin>();

    public virtual ICollection<MemberFavorite> MemberFavorites { get; set; } = new List<MemberFavorite>();

    public virtual ICollection<MemberPasswordResetToken> MemberPasswordResetTokens { get; set; } = new List<MemberPasswordResetToken>();

    public virtual ICollection<MemberRefreshToken> MemberRefreshTokens { get; set; } = new List<MemberRefreshToken>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<PreOrder> PreOrders { get; set; } = new List<PreOrder>();

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();

    public virtual ICollection<SubscriptionPreference> SubscriptionPreferences { get; set; } = new List<SubscriptionPreference>();

    public virtual ICollection<UserNotification> UserNotifications { get; set; } = new List<UserNotification>();

    public virtual ICollection<WalkInQueue> WalkInQueues { get; set; } = new List<WalkInQueue>();
}