// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EatTogether.API.Models.EfModels;

public partial class OrderDetail
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public int UnitPrice { get; set; }

    public int Qty { get; set; }

    public int SubTotal { get; set; }

    public int? ParentDetailId { get; set; }

    public int? PreOrderDetailId { get; set; }

    public virtual ICollection<OrderDetail> InverseParentDetail { get; set; } = new List<OrderDetail>();

    public virtual Order Order { get; set; }

    public virtual OrderDetail ParentDetail { get; set; }

    public virtual Product Product { get; set; }
}