// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EatTogether.API.Models.EfModels;

public partial class Payment
{
    public int Id { get; set; }

    public int? OrderId { get; set; }

    public int PreOrderId { get; set; }

    public string Method { get; set; }

    public DateTime PaidAt { get; set; }

    public int DoneOrCancel { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual PreOrder PreOrder { get; set; }

    public virtual ICollection<PreOrder> PreOrders { get; set; } = new List<PreOrder>();
}