// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EatTogether.API.Models.EfModels;

public partial class PreOrderDetail
{
    public int Id { get; set; }

    public int PreOrderId { get; set; }

    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public int UnitPrice { get; set; }

    public int Qty { get; set; }

    public int SubTotal { get; set; }

    public int DoneOrCancel { get; set; }

    public bool IsBilled { get; set; }

    public bool IsSetMeal { get; set; }

    public int? ParentDetailId { get; set; }

    public virtual ICollection<PreOrderDetail> InverseParentDetail { get; set; } = new List<PreOrderDetail>();

    public virtual PreOrderDetail ParentDetail { get; set; }

    public virtual PreOrder PreOrder { get; set; }

    public virtual Product Product { get; set; }
}