// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EatTogether.API.Models.EfModels;

public partial class Product
{
    public int Id { get; set; }

    public string ProductType { get; set; }

    public int? DishId { get; set; }

    public int? SetMealId { get; set; }

    public virtual Dish Dish { get; set; }

    public virtual ICollection<MemberFavorite> MemberFavorites { get; set; } = new List<MemberFavorite>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<PreOrderDetail> PreOrderDetails { get; set; } = new List<PreOrderDetail>();

    public virtual SetMeal SetMeal { get; set; }
}