// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EatTogether.API.Models.EfModels;

public partial class Reservation
{
    public int Id { get; set; }

    public string BookingNumber { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public DateTime ReservationDate { get; set; }

    public int AdultsCount { get; set; }

    public int ChildrenCount { get; set; }

    public int Status { get; set; }

    public string Remark { get; set; }

    public DateTime ReservedAt { get; set; }
}