// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EatTogether.API.Models.EfModels;

public partial class Review
{
    public int Id { get; set; }

    public int DishId { get; set; }

    public string Nickname { get; set; }

    public string Content { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Dish Dish { get; set; }
}