// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EatTogether.API.Models.EfModels;

public partial class RoleFunction
{
    public int Id { get; set; }

    public int RoleId { get; set; }

    public int FunctionId { get; set; }

    public virtual Function Function { get; set; }

    public virtual Role Role { get; set; }
}