// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EatTogether.API.Models.EfModels;

public partial class Role
{
    public int Id { get; set; }

    public string RoleName { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<RoleFunction> RoleFunctions { get; set; } = new List<RoleFunction>();

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}