// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EatTogether.API.Models.EfModels;

public partial class SchedulerLog
{
    public int Id { get; set; }

    public DateTime ExecutedAt { get; set; }

    public int DishesEnabled { get; set; }

    public int DishesDisabled { get; set; }

    public int MealsEnabled { get; set; }

    public int MealsDisabled { get; set; }

    public string TriggerType { get; set; }

    public string DetailJson { get; set; }
}