// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EatTogether.API.Models.EfModels;

public partial class UserNotification
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public string Type { get; set; }

    public string ReferenceType { get; set; }

    public int? ReferenceId { get; set; }

    public string Title { get; set; }

    public string Message { get; set; }

    public bool IsRead { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Member Member { get; set; }
}