// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EatTogether.API.Models.EfModels;

public partial class WalkInQueue
{
    public int Id { get; set; }

    public string QueueNumber { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public int AdultsCount { get; set; }

    public int ChildrenCount { get; set; }

    public int Status { get; set; }

    public string Remark { get; set; }

    public DateTime RegisteredAt { get; set; }

    public DateTime? CalledAt { get; set; }

    public DateTime? SeatedAt { get; set; }

    public DateTime? LeftAt { get; set; }

    public int? MemberId { get; set; }

    public int? TableId { get; set; }

    public virtual Member Member { get; set; }

    public virtual Table Table { get; set; }
}